using _01_DataAccessLayer.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _02_BusinessLogicLayer.DTOs.TimeSlotDTOs
{
    //DTO for creating a new time slot
    public class CreateTimeSlotDTO
    {
        // take care id will be generated by the database Auto Increment
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public WeekDays DayOfWeek { get; set; }
    }
}
