// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_DataAccessLayer.Data.Context;

#nullable disable

namespace _01_DataAccessLayer.Data.Migrations
{
    [DbContext(typeof(Re3ayaDbContext))]
    partial class Re3ayaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("DetailedAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CityId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            CityId = 1,
                            DetailedAddress = "5th Settlement",
                            DoctorId = 1,
                            Location = "Cairo"
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemInfoId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("SystemInfoId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            AppUserId = "3",
                            SystemId = 1
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Date_LessThan20YearsAgo", "DateOfBirth <= DATEADD(YEAR, -16, GETDATE())");
                        });

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2ddcc743-0809-4faf-936a-b410550f9b7f",
                            CreatedAt = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 5, 15),
                            Email = "ahmed@example.com",
                            EmailConfirmed = false,
                            FullName = "Ahmed Khaled",
                            Gender = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMED@EXAMPLE.COM",
                            NormalizedUserName = "AHMED@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOvDkuggRiUd9Xdo0Duj/enwiAk5AhB8Ksz8rR1iOEWN2bCh8VfGgsmTvRzGEyoxnA==",
                            PhoneNumber = "01234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1745186c-0e59-4796-af84-a4162219cf06",
                            TwoFactorEnabled = false,
                            UserName = "ahmed@example.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "53905215-6116-4c99-9d4f-8ac6d5b60350",
                            CreatedAt = new DateTime(2025, 7, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1985, 9, 22),
                            Email = "sara.ali@doc.com",
                            EmailConfirmed = false,
                            FullName = "Dr. Sara Ali",
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.ALI@DOC.COM",
                            NormalizedUserName = "SARA.ALI@DOC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENtOLscE6QaTjI3Op7q4E4dnYxbkouIBJRNoR8zUbEfwohsOxm8ayhbMNet19EIf+A==",
                            PhoneNumber = "01987654321",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4b2c44fb-7b6f-464a-bae6-811683b4491c",
                            TwoFactorEnabled = false,
                            UserName = "sara.ali@doc.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aea05986-3038-4000-aa2c-d5e18348ef44",
                            CreatedAt = new DateTime(2025, 7, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1980, 3, 10),
                            Email = "omar@admin.com",
                            EmailConfirmed = false,
                            FullName = "Admin Omar",
                            Gender = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "OMAR@ADMIN.COM",
                            NormalizedUserName = "OMAR@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMJZFV6JYG/C5oEGx57mt6WC/pQz61MTAUvHE4YxAtJ6dUWezgG10QWrI6IOHVfXHg==",
                            PhoneNumber = "01102682493",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "351d124b-b500-467f-b221-0e46170a68c8",
                            TwoFactorEnabled = false,
                            UserName = "omar@admin.com"
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorTimeSlotId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorTimeSlotId")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2025, 7, 19, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorTimeSlotId = 1,
                            Notes = "Initial visit",
                            PatientId = 1,
                            PaymentId = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<int>("GovernmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CityId");

                    b.HasIndex("GovernmentId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            GovernmentId = 1,
                            Name = "Cairo"
                        },
                        new
                        {
                            CityId = 2,
                            GovernmentId = 2,
                            Name = "Alexandria"
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("AboutMe")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<int?>("ExpYears")
                        .HasColumnType("int");

                    b.Property<double>("Fees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100.0);

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RatingValue")
                        .HasColumnType("real");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors", t =>
                        {
                            t.HasCheckConstraint("CK_NationalID_Length", "LEN(NationalID) = 14 AND NationalID NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_RatingValue_Range", "RatingValue >= 0 AND RatingValue <= 10");
                        });

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            AboutMe = "Experienced cardiologist with 10 years in heart care.",
                            AppUserId = "2",
                            Balance = 1500.0,
                            ExpYears = 10,
                            Fees = 500.0,
                            NationalId = "12345678901234",
                            RatingValue = 4.8f,
                            Service = 1,
                            SpecializationId = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.DoctorTimeSlot", b =>
                {
                    b.Property<int>("DoctorTimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorTimeSlotId"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.HasKey("DoctorTimeSlotId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("DoctorTimeSlots");

                    b.HasData(
                        new
                        {
                            DoctorTimeSlotId = 1,
                            DoctorId = 1,
                            IsAvailable = true,
                            TimeSlotId = 1
                        },
                        new
                        {
                            DoctorTimeSlotId = 2,
                            DoctorId = 1,
                            IsAvailable = true,
                            TimeSlotId = 2
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            DocumentId = 1,
                            DoctorId = 1,
                            DocumentType = 2,
                            FilePath = "cert_sara.pdf",
                            IsVerified = true,
                            UploadedAt = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DocumentId = 2,
                            DoctorId = 1,
                            DocumentType = 4,
                            FilePath = "id_sara.pdf",
                            IsVerified = true,
                            UploadedAt = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Government", b =>
                {
                    b.Property<int>("GovernmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GovernmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GovernmentId");

                    b.ToTable("Governments");

                    b.HasData(
                        new
                        {
                            GovernmentId = 1,
                            Name = "Cairo"
                        },
                        new
                        {
                            GovernmentId = 2,
                            Name = "Alexandria"
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PatientId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            AppUserId = "1"
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Amount_Positive", "Amount > 100");
                        });

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 500.0,
                            CreatedAt = new DateTime(2025, 7, 19, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TransactionId = 123456
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<float>("RatingValue")
                        .HasColumnType("real");

                    b.HasKey("RatingId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("RatingValue_Range", "RatingValue >= 0 AND RatingValue <= 10");
                        });

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Comment = "Great service!",
                            DoctorId = 1,
                            PatientId = 1,
                            RatingValue = 4.8f
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            Description = "Heart care",
                            Name = "Cardiology"
                        },
                        new
                        {
                            SpecializationId = 2,
                            Description = "Child care",
                            Name = "Pediatrics"
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.SystemInfo", b =>
                {
                    b.Property<int>("SystemInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemInfoId"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemInfoId");

                    b.ToTable("SystemInfos");

                    b.HasData(
                        new
                        {
                            SystemInfoId = 1,
                            Balance = 10000.0,
                            Email = "support@rea3ya.com",
                            Name = "Rea3ya",
                            PhoneNumber = "+20212345678"
                        });
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSlotId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlots", t =>
                        {
                            t.HasCheckConstraint("CK_TimeSlot_EndTime_After_StartTime", "EndTime > StartTime");
                        });

                    b.HasData(
                        new
                        {
                            TimeSlotId = 1,
                            DayOfWeek = 2,
                            EndTime = new DateTime(2025, 7, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 7, 21, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TimeSlotId = 2,
                            DayOfWeek = 3,
                            EndTime = new DateTime(2025, 7, 22, 17, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 7, 22, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_01_DataAccessLayer.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Address", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DataAccessLayer.Models.Doctor", "Doctor")
                        .WithMany("Addresses")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Admin", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.AppUser", "AppUser")
                        .WithOne("Admin")
                        .HasForeignKey("_01_DataAccessLayer.Models.Admin", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_01_DataAccessLayer.Models.SystemInfo", null)
                        .WithMany("Admins")
                        .HasForeignKey("SystemInfoId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Appointment", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.DoctorTimeSlot", "DoctorTimeSlot")
                        .WithOne("Appointment")
                        .HasForeignKey("_01_DataAccessLayer.Models.Appointment", "DoctorTimeSlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_01_DataAccessLayer.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_01_DataAccessLayer.Models.Payment", "Payment")
                        .WithOne("Appointment")
                        .HasForeignKey("_01_DataAccessLayer.Models.Appointment", "PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DoctorTimeSlot");

                    b.Navigation("Patient");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.City", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.Government", "Government")
                        .WithMany("Cities")
                        .HasForeignKey("GovernmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Government");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Doctor", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.AppUser", "AppUser")
                        .WithOne("Doctor")
                        .HasForeignKey("_01_DataAccessLayer.Models.Doctor", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_01_DataAccessLayer.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.DoctorTimeSlot", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.Doctor", "Doctor")
                        .WithMany("DoctorTimeSlots")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_01_DataAccessLayer.Models.TimeSlot", "TimeSlot")
                        .WithMany("DoctorTimeSlots")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Document", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.Doctor", "Doctor")
                        .WithMany("Documents")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Patient", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.AppUser", "AppUser")
                        .WithOne("Patient")
                        .HasForeignKey("_01_DataAccessLayer.Models.Patient", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Rating", b =>
                {
                    b.HasOne("_01_DataAccessLayer.Models.Doctor", "Doctor")
                        .WithMany("Ratings")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_01_DataAccessLayer.Models.Patient", "Patient")
                        .WithMany("Ratings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.AppUser", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Doctor", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("DoctorTimeSlots");

                    b.Navigation("Documents");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.DoctorTimeSlot", b =>
                {
                    b.Navigation("Appointment")
                        .IsRequired();
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Government", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Payment", b =>
                {
                    b.Navigation("Appointment")
                        .IsRequired();
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.SystemInfo", b =>
                {
                    b.Navigation("Admins");
                });

            modelBuilder.Entity("_01_DataAccessLayer.Models.TimeSlot", b =>
                {
                    b.Navigation("DoctorTimeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
